version: '3'
services:
  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rainbow_database
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data locally
volumes:
  database-data: # named volume