version: '3'
services:
  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data locally
volumes:
  database-data: # named volumes ca